### GET ALL
get http://localhost:3000/users/ http/1.1


### SIGNUP
post http://localhost:3000/users/signup http/1.1
Content-Type: application/json

{
    "name": "Ali",
    "email": "ali9@gmail.com",
    "password": "123456"
}